<?php
 
use Drupal\Core\Routing\RouteMatchInterface;
/**

* Implements hook_form_alter().

*/
 
function first_module_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){

  if($form_id = 'user-login-form'){

    $form['#title'] = t('Login with your info');
    $form['name']['#attributes']['placeholder'] = t('Enter your username');
    $form['pass']['#attributes']['placeholder'] = t('************');

  }
 
}
/**
* Implements hook_preprocess_page().
**/
 
function first_module_preprocess_page(&$variables) {
    $variables['first_module_variable'] = 'My First D10 Module';
}

function first_module_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
        case 'help.page.first_module':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('This is a first custom module hook_help') . '</p>';
            return $output;
        default:
    }
}

 
 
 
?>
 